# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:7861/sdapi/v1/txt2img
Content-Type: application/json
Accept: application/json

{
  "prompt": "a cyberpunk city at night, neon lights, rain",
  "steps": 20
}

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/photo/a penguin going for its first swim/20/7.5/
Accept: application/json

###

GET http://127.0.0.1:8000/image
Accept: application/json

###

GET http://127.0.0.1:8000/secure-endpoint/Bogus_Key/
Accept: application/json

###
