# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/photo/a penguin going for its first swim/20/7.5/
Accept: application/json

###

GET http://127.0.0.1:8000/image
Accept: application/json

###

GET http://127.0.0.1:8000/secure-endpoint/Bogus_Key/
Accept: application/json

###
